language: java
#jdk: openjdk14 #problems with sonar-maven-plugin
branches:
  only:
    - develop
    - "/^Release-[0-999].[0-999]$/"
    - master
notifications:
  slack: 'upm-aup7245:zoVK0RcTvVTZweOb39hMqijD#miw-devops-eric-aldas'
  email:
    recipients:
      - e.aldas@alumnos.upm.es
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn verify sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=walericalupm -Dsonar.login=$SONAR
deploy:
  provider: heroku
  api_key: $HEROKU
  on:
    branch: master
